from flask import Flask, request, jsonify, render_template
from gtts import gTTS
import os

app = Flask(__name__)

# Sample responses based on keywords
responses = {
    "hello": "Hello! Welcome to our health chat service. It's a pleasure to have you here, and I'm dedicated to providing necessary assistance and guidance to alleviate any of your health-related concerns. How are you feeling today?",
    "not well": "Are you having any pain or discomfort?",
    "nothing like that": "Any coughing,congestion or difficulty in breathing?",
    "yeah it is there": "Have you seen any other doctors for this?",
    "no one like that": "what is your main concern?",
    "illness": "Illness is an experience related to a person's neural sensitivity and high-level stability that places them in a specific position.",
    "thank you": "You're welcome! Remember, and keep in mind, you are not alone on this journey. We are here to support you every step of the way. Wishing you better health and vitality. Until next time, goodbye!",
    "Back pain Causes": "Overuse, improper lifting, or sudden movements can strain the muscles or ligaments in the back. A condition where bones become porous and brittle, increasing the risk of fractures. Conditions like scoliosis can cause back pain.",
    "Back pain Symptoms": "It may be localized to one area or may radiate to other parts of the body. Strengthening core muscles can help support the spine and prevent injury. Difficulty in standing up straight or performing certain activities.",
    "Back pain Prevention": "Avoid slouching or sitting for extended periods without breaks. Bend at the knees and lift with your legs rather than your back. Strengthening core muscles can help support the spine and prevent injury. Chairs and desks that support good posture can help prevent back strain.",
    "Back pain Medicine": "Nonsteroidal Anti-Inflammatory Drugs Examples include ibuprofen and naproxen. Opioids:Examples include oxycodone and hydrocodone.",
    "Food poisoning Causes": " Common bacterial causes include Salmonella, E.coli, Campylobacter, and Listeria. Viral pathogens like norovirus and hepatitis A can also cause food poisoning.Parasitic infections such as Giardia and Cryptosporidium can be transmitted through contaminated food or water.",
    "Food poisoning Symptoms": "Nausea, vomiting, diarrhea, abdominal cramps, and stomach pain. Symptoms can range from mild discomfort to severe illness requiring hospitalization, depending on the causative agent and individual factors. Fever, headache, muscle aches, and fatigue.",
    "Food poisoning Prevention": " Wash hands and surfaces often, separate raw meats from other foods, cook foods to proper temperatures, and refrigerate perishable foods promptly. Drink plenty of fluids to prevent dehydration caused by vomiting and diarrhea. Get adequate rest to allow the body to recover.",
    "Food poisoning Medicine": "Anti-diarrheal medications like loperamide to reduce diarrhea. Antiemetics like ondansetronto relieve nausea and vomiting. Acetaminophen for fever and muscle aches.",
    "Dry eyes Causes": "Tear production tends to diminish with age, leading to dry eyes. Prolonged use of digital screens or contact lenses can lead to dry eyes. Antihistamines, decongestants, antidepressants, and certain blood pressure medications can reduce tear production. Exposure to wind, smoke, dry air, or air conditioning can cause tears to evaporate more quickly.",
    "Dry eyes Symptoms": " Irritation or discomfort in the eyes. Eyes may appear red or bloodshot. Increased sensitivity to light, especially in bright environments. Sensation of gritty or scratchy eyes.",
    "Dry eyes Prevention": "Blinking helps spread tears evenly over the surface of the eyes. Adding moisture to the air with a humidifier can help prevent dryness, especially in dry indoor environments. When using digital screens or performing tasks that require prolonged focus, take regular breaks to rest your eyes.",
    "Dry eyes Medicine": "Prescription Eye Drops:Examples include:Cyclosporine,Lifitegrast. In cases of severe inflammation, short-term use of steroid eye drops may be prescribed to reduce swelling and discomfort.",
    "Common cold Causes": "The common cold is most often caused by viruses, with rhinoviruses being the most common culprits. Other viruses, such as coronaviruses and adenoviruses, can also cause colds. Colds are highly contagious and spread through respiratory droplets when an infected person coughs, sneezes, or talks. They can also be spread by touching surfaces contaminated with the virus and then touching the nose, mouth, or eyes.",
    "Common cold Symptoms": "Stuffy or runny nose is a hallmark symptom. Frequent sneezing may occur. Irritation or scratchiness in the throat. Mild muscle aches and pains may be present. Some people may experience a slight increase in body temperature.",
    "Common cold Prevention": "Wash hands frequently with soap and water for at least 20 seconds, especially after coughing, sneezing, or touching surfaces. Limit close contact with people who have cold symptoms. Use a tissue or the crook of your elbow to cover your mouth and nose when coughing or sneezing. Avoid touching your eyes, nose, and mouth with unwashed hands.",
    "Common cold Medicine": "Some cough suppressants may help relieve cough symptoms. Examples include dextromethorphan. Can help relieve nasal congestion. Examples include pseudoephedrine and phenylephrine. May help reduce sneezing and runny nose. Examples include diphenhydramine and loratadine.",
    "Dandruff Causes": "A yeast-like fungus that commonly lives on the scalp and may contribute to dandruff when it grows out of control. Not washing the hair frequently enough can lead to a buildup of oil and dead skin cells, exacerbating dandruff. Dry scalp can cause flakes to shed more easily.",
    "Dandruff Symptoms": "Small white or gray flakes of dead skin that may be visible on the scalp, hair, or shoulders. The scalp may feel itchy or irritated, leading to scratching. In some cases, dandruff may be accompanied by redness or inflammation of the scalp.",
    "Dandruff Prevention": " Washing the hair regularly with a mild shampoo can help remove excess oil and dead skin cells from the scalp. Using shampoos containing ingredients like zinc pyrithione, selenium sulfide, ketoconazole, or coal tar can help control dandruff. Avoid using harsh hair care products or those containing alcohol, which can dry out the scalp.",
    "Dandruff Medicine": "In cases of severe inflammation or seborrheic dermatitis, doctors may prescribe topical steroids to reduce inflammation and itching. In severe cases of dandruff or seborrheic dermatitis, oral antifungal medications may be prescribed to help control fungal growth.",
    "Muscle pain Causes": " Strain or injury from overuse of muscles during physical activity or sports. Tension or tightness in muscles due to stress, poor posture, or prolonged sitting or standing.",
    "Muscle pain Symptoms": " Pain or soreness in specific muscles or muscle groups. Difficulty moving or stiffness in affected muscles. Swelling, tenderness, or bruising around the affected areaDifficulty with certain movements due to pain or stiffness..",
    "Muscle pain Prevention": " Always warm up before exercising or engaging in physical activity to prepare muscles and reduce the risk of injury. Incorporate regular stretching exercises to improve flexibility and reduce muscle tension. Drink plenty of water to keep muscles hydrated and functioning properly.",
    "Muscle pain Medicine": "Nonsteroidal anti-inflammatory drugs such as ibuprofen or naproxen can help reduce pain and inflammation. Creams, gels, or patches containing ingredients like menthol, capsaicin, or lidocaine can provide localized relief from muscle pain.",
    "Sore throat Causes": "The most common cause of a sore throat is a viral infection, such as the common cold, flu, or infectious mononucleosis. Allergies to pollen, mold, pet dander, or other allergens can lead to throat irritation and soreness. Dry air, smoking, air pollution, or exposure to irritants can contribute to a sore throat. Acid reflux can cause irritation and inflammation of the throat lining.",
    "Sore throat Symptoms": "Soreness, pain, or scratchiness in the throat. Swallowing may be painful or uncomfortable. The throat may appear red and swollen. Changes in voice quality or hoarseness may occur. Depending on the underlying cause, additional symptoms such as cough, fever, runny nose, sneezing, or fatigue may be present.",
    "Sore throat Prevention": "Wash hands frequently, especially during cold and flu seasons, to reduce the risk of viral infections. Avoid close contact with individuals who have respiratory infections. Avoid smoking and exposure to secondhand smoke, as it can irritate the throat. Use a humidifier to add moisture to indoor air, especially during dry weather.",
    "Sore throat Medicine": "If the sore throat is caused by a bacterial infection, such as strep throat, the doctor may prescribe antibiotics like penicillin or amoxicillin.Over-the-counter pain relievers such as ibuprofen or acetaminophen can help alleviate pain and reduce inflammation. Throat lozenges containing numbing agents like benzocaine or throat sprays containing topical anesthetics can provide temporary relief from sore throat pain. If allergies are contributing to the sore throat, antihistamines may be recommended to alleviate symptoms.",
    "Acne Causes": "Overproduction of oil by the sebaceous glands can clog pores and contribute to acne. Dead skin cells and bacteria can accumulate in the pores, leading to blockages. Propionibacterium acnes bacteria can proliferate within blocked pores, leading to inflammation and acne. Family history can play a role in predisposing individuals to acne.",
    "Acne Symptoms": "Red, swollen bumps, pus-filled lesions, and deeper, painful nodules or cysts may appear on the skin. Open comedones and closed comedones may develop when pores become clogged with oil and dead skin cells. Severe acne can lead to permanent scarring or hyperpigmentation if not properly treated.",
    "Acne Prevention": "Washing the face twice daily with a gentle cleanser can help remove excess oil, dirt, and bacteria without stripping the skin. Apply a broad-spectrum sunscreen daily to protect the skin from UV damage and prevent post-inflammatory hyperpigmentation. Maintain a balanced diet, stay hydrated, manage stress, and avoid smoking, as these factors can influence acne severity.",
    "Acne Medicine": "Tretinoin, adapalene and tazarotene are topical medications derived from vitamin A. They work by preventing pore blockages, reducing inflammation, and promoting skin cell turnover. Doxycycline, minocycline, and tetracycline are oral antibiotics prescribed for moderate to severe acne to reduce inflammation and bacterial growth. Isotretinoin is a potent oral medication reserved for severe, cystic acne that is resistant to other treatments. It works by reducing oil production, preventing clogged pores, and inhibiting P. acnes bacteria.",
    "Tooth ache Causes": "Fluctuations in hormone levels, especially during puberty, menstruation, or pregnancy, can contribute to acne around the mouth. Not properly cleaning the mouth, teeth, and chin area can lead to the accumulation of bacteria and oils, resulting in acne. Certain foods, especially those high in sugar or processed carbohydrates, may exacerbate acne.",
    "Tooth ache Symptoms": "Red, inflamed bumps or pustules may develop around the mouth or chin area. These may appear as small, dark spots (blackheads) or white bumps. Acne lesions may be tender or painful to touch. In severe cases, acne lesions may lead to scarring if not properly treated.",
    "Tooth ache Prevention": "Brush teeth twice a day, floss regularly, and use mouthwash to keep the mouth clean and prevent bacteria buildup. Touching the face with dirty hands can transfer bacteria and oils, leading to acne formation. Eat a balanced diet rich in fruits, vegetables, lean proteins, and whole grains, and limit sugary and processed foods. Practice stress-reduction techniques such as mindfulness, meditation, or yoga to help prevent hormonal imbalances.",
    "Tooth ache Medicine": "Over-the-counter or prescription topical medications containing ingredients like benzoyl peroxide, salicylic acid, or retinoids can help reduce acne lesions. Dermatological procedures such as chemical peels, microdermabrasion, or laser therapy may be recommended for severe or persistent acne. In some cases, a doctor may prescribe oral antibiotics or oral contraceptives to help control hormonal acne.",
    "Mouth ulcer Causes": "Accidental biting, aggressive tooth brushing, or dental work can cause trauma to the mouth, leading to ulcer formation. Certain foods, such as acidic or spicy foods, or oral hygiene products containing sodium lauryl sulfate, can irritate the mouth and trigger ulcers. Conditions like autoimmune diseases, gastrointestinal disorders, or viral infections may be associated with recurrent mouth ulcers. Lack of essential nutrients like vitamin B12, iron, or folate can contribute to ulcer formation.",
    "Mouth ulcer Symptoms": "Mouth ulcers are typically painful, especially when eating, drinking, or brushing teeth. Ulcers are usually round or oval-shaped with a white or yellowish center and a red border. Severe ulcers may interfere with normal activities like eating and speaking. Inflammation and swelling of the surrounding tissue may accompany mouth ulcers.",
    "Mouth ulcer Prevention": "Brush teeth gently with a soft-bristled toothbrush and avoid irritating the mouth. Limit consumption of acidic, spicy, or abrasive foods that may trigger ulcer formation. Both tobacco and alcohol can irritate the mouth and increase the risk of ulcers.Ensure a balanced diet rich in vitamins and minerals to support oral health.",
    "Mouth ulcer Medicine": "Over-the-counter or prescription topical gels or ointments containing ingredients like benzocaine or lidocaine can provide pain relief. Prescription-strength corticosteroid mouth rinses or ointments may be prescribed to reduce inflammation and promote healing. In severe cases or for recurrent ulcers, doctors may prescribe systemic medications like corticosteroids, immunomodulators, or antiviral drugs to manage underlying conditions or suppress immune responses.",
    "Indigestion Causes": "Eating too much or too quickly, consuming fatty, greasy, or spicy foods, and drinking alcohol or caffeine can contribute to indigestion. Gastroesophageal reflux disease, peptic ulcers, gastritis, gallstones, and pancreatitis can cause indigestion. Certain medications, such as nonsteroidal anti-inflammatory drugs,antibiotic and bisphosphonates may irritate the stomach lining and lead to indigestion.",
    "Indigestion Symptoms": "Burning sensation or pain in the upper abdomen. Feeling of fullness or bloating after eating. Feeling sick to the stomach or experiencing the urge to vomit. Excessive belching or passing gas.Burning sensation in the chest, especially after eating or lying down.",
    "Indigestion Prevention": "Eat smaller, more frequent meals, avoid trigger foods, and chew food slowly and thoroughly. Excess weight can put pressure on the stomach and worsen indigestion symptoms. Reduce alcohol and caffeine intake, as they can irritate the stomach lining. Smoking can increase stomach acid production and weaken the lower esophageal sphincter, leading to indigestion.",
    "Indigestion Medicine": "Antacids:Examples include calcium carbonate, magnesium hydroxide and aluminum hydroxide. Antacids neutralize stomach acid and provide quick relief from indigestion symptoms. Prokinetics:Examples include metoclopramide and domperidone.",
    "Ear ache Causes": "Ear infections, such as otitis media or otitis externa can cause earaches. Trauma to the ear, such as a blow to the ear or insertion of foreign objects, can result in pain. Excessive earwax can block the ear canal, leading to discomfort or pain. Rapid changes in air pressure, such as during air travel or scuba diving, can cause ear pain.",
    "Ear ache Symptoms": "Sharp or dull pain in the ear, which may be constant or intermittent. Partial or complete hearing loss in the affected ear. Fluid drainage from the ear, which may be clear, yellow, or bloody, depending on the underlying cause. In cases of ear infection, fever may accompany the earache.Ringing, buzzing, or other noises in the ear.",
    "Ear ache Prevention": "Avoid inserting objects into the ear canal to clean earwax, as this can push wax deeper or cause injury. Use earplugs or earmuffs in noisy environments and wear swim caps or earplugs while swimming to prevent water from entering the ears. Addressing allergies can help reduce congestion and minimize the risk of ear infections. Chew gum, swallow, or yawn during takeoff and landing to equalize ear pressure.",
    "Ear ache Medicine": "Over-the-counter pain relievers like acetaminophen or ibuprofen can help alleviate ear pain. Oral or nasal decongestants may be prescribed to relieve congestion and promote drainage in cases of eustachian tube dysfunction.",
    "Injury to abdomen Causes": "Blunt force trauma from accidents, falls, or assaults can cause abdominal injuries. Stab or gunshot wounds can puncture abdominal organs. Conditions like appendicitis, pancreatitis, or liver disease can cause abdominal pain or injury. Complications from surgeries or medical procedures can result in abdominal injuries.",
    "Injury to abdomen Symptoms": "Abdominal pain, tenderness, or soreness, which may worsen with movement or pressure. Visible swelling or bruising in the abdominal area. Feeling nauseous or vomiting, especially if accompanied by blood. Feeling weak, lightheaded, or fatigued, which may indicate internal bleeding.",
    "Injury to abdomen Prevention": " Wear seat belts in vehicles, use appropriate safety gear during sports or recreational activities. Avoid risky behaviors such as excessive alcohol consumption or participating in violent activities. Lift heavy objects with proper technique to prevent strain on the abdomen. Maintain a healthy weight and lifestyle to reduce the risk of conditions that can lead to abdominal injuries.",
    "Injury to abdomen Medicine": "Nonsteroidal anti-inflammatory drugs (NSAIDs) such as ibuprofen or acetaminophen may be prescribed to manage pain and inflammation. Medications like cyclobenzaprine may be prescribed to relax abdominal muscles and alleviate discomfort. Medications to control nausea and vomiting, such as ondansetron, may be given if these symptoms are present.",
    "Injury to hand Causes": " Falls, crush injuries, sports-related accidents, and workplace incidents are common causes of hand injuries. Motor vehicle accidents, machinery mishaps, and household accidents can result in hand injuries. Overuse or repetitive motions, such as typing or using hand tools, can lead to conditions like carpal tunnel syndrome or tendonitis. Sharp objects or tools can cause cuts, puncture wounds, or lacerations to the hand.",
    "Injury to hand Symptoms": "Persistent or acute pain in the hand or fingers. Swelling or inflammation around the injured area. Discoloration of the skin due to bleeding under the skin. Difficulty moving the hand or fingers. Visible deformity or misalignment of the hand or fingers.",
    "Injury to hand Prevention": "Wear appropriate protective gear, such as gloves or hand guards, when engaging in activities with a risk of hand injury. Learn and practice proper techniques for using tools and equipment to reduce the risk of accidents and repetitive strain injuries. Be mindful of potential hazards in the environment, such as slippery surfaces or sharp objects, and take precautions to prevent accidents.",
    "Injury to hand Medicine": "Nonsteroidal anti-inflammatory drugs (NSAIDs) like ibuprofen or acetaminophen may be prescribed to relieve pain and reduce inflammation. If the injury involves an open wound or there is a risk of infection, antibiotics may be prescribed to prevent or treat infection."

}


def get_response(message):
    message = message.lower()
    for keyword in responses:
        if keyword.lower() in message:
            return responses[keyword]
    return "Sorry, I couldn't understand."


@app.route('/')
def index():
    return render_template('index.html')


@app.route('/speech', methods=['POST'])
def speech():
    message = request.json['message']
    response_text = get_response(message)

    # Generate speech response
    speech_response = gTTS(text=response_text, lang='en', slow=False)
    speech_response.save("response.mp3")

    return jsonify({'response_text': response_text, 'response_speech': 'response.mp3'})


if __name__ == '__main__':
    app.run(host='0.0.0.0' , port=3000)
